[package]
name = "pg_perf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.5"
rand = "0.8.5"
rust_decimal = "1.29.1"
stopwatch = "0.0.7"
